import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export class HookManager {
    private context: vscode.ExtensionContext;
    private hookId: string;

    constructor(context: vscode.ExtensionContext) {
        this.context = context;

        // Get or generate unique hook ID
        let hookId = context.globalState.get<string>('hookId');
        if (!hookId) {
            hookId = this.generateHookId();
            context.globalState.update('hookId', hookId);
        }
        this.hookId = hookId;
    }

    /**
     * Generate a unique hook identifier
     */
    private generateHookId(): string {
        return Math.random().toString(36).substring(2, 10);
    }

    /**
     * Get the hook filename with identifier
     */
    private getHookFilename(): string {
        return `play-sound-cc-ring-${this.hookId}.sh`;
    }

    /**
     * Get the config filename
     */
    private getConfigFilename(): string {
        return `cc-ring-config-${this.hookId}.json`;
    }

    /**
     * Get the Claude Code hooks directory path (global only)
     */
    private getHooksDirectory(): string {
        return path.join(os.homedir(), '.claude', 'hooks');
    }

    /**
     * Get the Claude Code settings file path (global only)
     */
    private getSettingsPath(): string {
        return path.join(os.homedir(), '.claude', 'settings.json');
    }

    /**
     * Write config file with current sound and volume settings
     */
    async writeConfigFile(): Promise<void> {
        try {
            const config = vscode.workspace.getConfiguration('cc-ring');
            const volume = (config.get('volume', 50) / 100).toFixed(2);
            const sound = config.get<string>('sound', 'complete');
            const customSoundPath = config.get<string>('customSoundPath', '');

            // Get sound file path
            let soundPath: string;
            if (sound === 'custom' && customSoundPath) {
                soundPath = customSoundPath;
            } else {
                // Use bundled sound from extension
                const soundsDir = path.join(this.context.extensionPath, 'sounds');
                soundPath = path.join(soundsDir, `${sound}.wav`);
            }

            const hooksDir = this.getHooksDirectory();
            const configFilename = this.getConfigFilename();
            const configPath = path.join(hooksDir, configFilename);

            // Ensure hooks directory exists
            if (!fs.existsSync(hooksDir)) {
                fs.mkdirSync(hooksDir, { recursive: true });
            }

            // Write config file
            const configData = {
                soundPath,
                volume
            };

            fs.writeFileSync(configPath, JSON.stringify(configData, null, 2));
        } catch (error) {
            throw new Error(`Failed to write config file: ${error}`);
        }
    }

    /**
     * Generate the play-sound.sh script content
     */
    private generateHookScript(): string {
        const hooksDir = this.getHooksDirectory();
        const configFilename = this.getConfigFilename();
        const configPath = path.join(hooksDir, configFilename);

        // Get default sound path as fallback
        const soundsDir = path.join(this.context.extensionPath, 'sounds');
        const defaultSoundPath = path.join(soundsDir, 'complete.wav');

        return `#!/bin/bash

# CC Ring - Claude Code Sound Notifier Hook (macOS only)
# Auto-generated by VS Code extension
# Reads sound configuration from JSON file

CONFIG_FILE="${configPath}"
DEFAULT_SOUND="${defaultSoundPath}"
DEFAULT_VOLUME="0.50"

# Read config from JSON file
if [[ -f "$CONFIG_FILE" ]]; then
    # Extract soundPath and volume from JSON using basic parsing
    SOUND_FILE=$(grep -o '"soundPath"[[:space:]]*:[[:space:]]*"[^"]*"' "$CONFIG_FILE" | sed 's/.*"soundPath"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/')
    VOLUME=$(grep -o '"volume"[[:space:]]*:[[:space:]]*"[^"]*"' "$CONFIG_FILE" | sed 's/.*"volume"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/')

    # Use defaults if extraction failed
    if [[ -z "$SOUND_FILE" ]]; then
        SOUND_FILE="$DEFAULT_SOUND"
    fi
    if [[ -z "$VOLUME" ]]; then
        VOLUME="$DEFAULT_VOLUME"
    fi
else
    # Config file doesn't exist, use defaults
    SOUND_FILE="$DEFAULT_SOUND"
    VOLUME="$DEFAULT_VOLUME"
fi

# Fallback to macOS system sound if file doesn't exist
if [[ ! -f "$SOUND_FILE" ]]; then
    SOUND_FILE="/System/Library/Sounds/Ping.aiff"
fi

# Play sound using afplay
afplay -v "$VOLUME" "$SOUND_FILE" &>/dev/null &

exit 0
`;
    }

    /**
     * Install the Claude Code hook
     */
    async installHook(): Promise<void> {
        try {
            const hooksDir = this.getHooksDirectory();
            const hookFilename = this.getHookFilename();
            const hookScriptPath = path.join(hooksDir, hookFilename);

            // Ensure hooks directory exists
            if (!fs.existsSync(hooksDir)) {
                fs.mkdirSync(hooksDir, { recursive: true });
            }

            // Write hook script
            const scriptContent = this.generateHookScript();
            fs.writeFileSync(hookScriptPath, scriptContent, { mode: 0o755 });

            // Write config file with current settings
            await this.writeConfigFile();

            // Update Claude Code settings.json to register the hook
            await this.registerHook();

            console.log('Hook installed successfully at:', hookScriptPath);
        } catch (error) {
            throw new Error(`Failed to install hook: ${error}`);
        }
    }

    /**
     * Register the hook in Claude Code settings.json
     */
    private async registerHook(): Promise<void> {
        const settingsPath = this.getSettingsPath();
        const settingsDir = path.dirname(settingsPath);

        // Ensure settings directory exists
        if (!fs.existsSync(settingsDir)) {
            fs.mkdirSync(settingsDir, { recursive: true });
        }

        // Read existing settings or create new
        let settings: any = {};
        if (fs.existsSync(settingsPath)) {
            const content = fs.readFileSync(settingsPath, 'utf8');
            try {
                settings = JSON.parse(content);
            } catch (error) {
                console.warn('Failed to parse settings.json, creating new');
                settings = {};
            }
        }

        // Add hook configuration
        if (!settings.hooks) {
            settings.hooks = {};
        }

        // Use global absolute path
        const hookFilename = this.getHookFilename();
        const hookCommand = path.join(os.homedir(), '.claude', 'hooks', hookFilename);

        settings.hooks.Stop = [
            {
                hooks: [
                    {
                        type: 'command',
                        command: hookCommand,
                        timeout: 5
                    }
                ]
            }
        ];

        // Write updated settings
        fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    }

    /**
     * Uninstall the Claude Code hook
     */
    async uninstallHook(): Promise<void> {
        try {
            const hooksDir = this.getHooksDirectory();
            const hookFilename = this.getHookFilename();
            const hookScriptPath = path.join(hooksDir, hookFilename);

            // Remove hook script if it exists
            if (fs.existsSync(hookScriptPath)) {
                fs.unlinkSync(hookScriptPath);
            }

            // Remove hook from settings.json
            await this.unregisterHook();

            console.log('Hook uninstalled successfully');
        } catch (error) {
            throw new Error(`Failed to uninstall hook: ${error}`);
        }
    }

    /**
     * Unregister the hook from Claude Code settings.json
     */
    private async unregisterHook(): Promise<void> {
        const settingsPath = this.getSettingsPath();

        if (!fs.existsSync(settingsPath)) {
            return; // Nothing to do
        }

        try {
            const content = fs.readFileSync(settingsPath, 'utf8');
            const settings = JSON.parse(content);

            if (settings.hooks && settings.hooks.Stop) {
                delete settings.hooks.Stop;

                // If hooks object is now empty, remove it
                if (Object.keys(settings.hooks).length === 0) {
                    delete settings.hooks;
                }

                fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
            }
        } catch (error) {
            console.warn('Failed to unregister hook from settings.json:', error);
        }
    }

    /**
     * Check if hook is currently installed
     */
    isHookInstalled(): boolean {
        const hooksDir = this.getHooksDirectory();
        const hookFilename = this.getHookFilename();
        const hookScriptPath = path.join(hooksDir, hookFilename);
        return fs.existsSync(hookScriptPath);
    }
}
